# Generated by Django 5.0.2 on 2025-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='nouvelle description', max_length=255),
            preserve_default=False,
        ),
    ]
